name: Sync with eunii2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout eunii3 repo
        uses: actions/checkout@v2
        with:
          repository: eunii3/codetree-TILs
          ref: main

      - name: Sync with eunii2
        run: |
          git config --global user.name "eunii3"
          git config --global user.email "eunii3@example.com"
          git remote add eunii2 https://github.com/eunii2/codetree-TILs.git
          git fetch eunii2
          git merge --no-ff eunii2/main
          git push eunii2 main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

