name: Sync with eunii2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure git
        run: |
          git config --global user.name "eunii3"
          git config --global user.email "rose021223@chungbuk.ac.kr"

      - name: Add eunii2 remote and push changes
        run: |
          git remote add eunii2 https://eunii2:${{ secrets.EUNII2_PAT }}@github.com/eunii2/codetree-TILs.git
          git fetch eunii2
          git merge --no-ff --allow-unrelated-histories eunii2/main || true
          git push eunii2 main
