name: Sync with eunii2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # OpenSSL 설치
      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      # SSH_PRIVATE_KEY 디버그 (Secrets 제대로 로드되었는지 확인)
      - name: Debug SSH_PRIVATE_KEY
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -c 10

      # SSH 설정 및 에이전트 실행
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      # SSH 연결 테스트
      - name: Test SSH connection
        run: ssh -T git@github.com || true

      # Git 설정
      - name: Configure git
        run: |
          git config --global user.name "eunii3"
          git config --global user.email "rose021223@chungbuk.ac.kr"

      # 원격 저장소 추가 및 변경사항 푸시
      - name: Add eunii2 remote and push changes
        run: |
          git remote add eunii2 git@github.com:eunii2/codetree-TILs.git
          git fetch eunii2
          git merge --no-ff --allow-unrelated-histories eunii2/main || true
          git push eunii2 main
