name: Sync with eunii2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout eunii3 repository
        uses: actions/checkout@v2
        with:
          repository: eunii3/codetree-TILs  # eunii3 레포지토리를 명시적으로 체크아웃
          token: ${{ secrets.GITHUB_TOKEN }}  # 자동으로 생성된 GITHUB_TOKEN 사용

      # SSH 키 설정 및 디버깅
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      # SSH 연결 테스트
      - name: Test SSH connection
        run: ssh -T git@github.com || true

      # Git 설정 - eunii2로 커밋을 표시
      - name: Configure git for eunii2
        run: |
          git config --global user.name "eunii2"
          git config --global user.email "eunii2@example.com"

      # 원격 저장소 추가 및 변경사항 푸시 (eunii3의 내용으로 덮어쓰기)
      - name: Add eunii2 remote and push changes
        run: |
          git remote add eunii2 git@github.com:eunii2/codetree-TILs.git
          git fetch eunii3
          git reset --hard eunii3/main  # eunii3의 내용을 덮어씌우기
          git push eunii2 main --force-with-lease  # eunii2로 강제 푸시
